### ISSUE TITLE
Replace @ef-carbon/tspm dependency with "tscpaths"

### ISSUE THREAD

**Issue by Veetaha** [akrava/birthday-tg-bot#1]
Tspm package ceased being maintained a year ago and it conflicts with the latest ECMAscript language standards (e.g. it crashes on the use of object spread operator).
Though ["tscpaths"](https://www.npmjs.com/package/tscpaths) was updated 4 months ago it seems to work well with new language features and is more preferable from my point of view.

**Comment by akrava** [comment]
Thanks for the feedback of this project.
Due to this package doesn't cause conflicts now, it will be fixed with the next submissions. Although, I appreciate you for this advice and I'll keep it on mind.
